### ISSUE TITLE
I2C Reset Pin Support

### ISSUE THREAD

**Issue by Davincible** [Seeed-Studio/Seeed_Arduino_NFC#2]
Would be great to have support for the reset pin, as implemented here:
https://github.com/Seeed-Studio/PN532/pull/33

It's quite trivial for the esp32 + pn532 as the I2C bus gets stuck on reset otherwise

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

The reset pin is not currently supported, and the PR you mention is not currently being merged.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
