### ISSUE TITLE
using arduino due

### ISSUE THREAD

**Issue by MaximeTasset** [Seeed-Studio/Seeed_Arduino_NFC#3]
Hi,
In a project that I currently develop, I want to use four Groove NFC modules linked to an Arduino Due to read and write ISO 14443-A/NFC tags
However, a lot of error arise when I'm trying to compile even an exemple sketch.
Is this library compatible with the arduino Due?

Best regards

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
